name: 'Announcement engige'
on: [push, pull_request]
jobs:
  build:
    runs-on: ubunntu-20.04

  name: Environment setup
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    with:
      python-version-file: '.python-version'
    
    - name: Buildout
      run: pip install -r requirements.txt
      run: buildout


